version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db_${APP_NAME}
    env_file:
      - variables.env
    ports:
      - "${EXTERNAL_DB_PORT}:3306"
  web:
    build: ./centos
    container_name: web_${APP_NAME}
    depends_on:
      - db
    env_file:
      - variables.env
    volumes:
      - ${APP_PATH}:/app/
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    networks:
      frontend:
          ipv4_address: 172.20.0.${IP_COUNTER}
    stdin_open: true
    tty: true

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
